
import React from 'react';
import {
  Home, TrendingUp, PiggyBank, BookOpen, Gamepad2, Gift,
  Briefcase, Car, Plane, GraduationCap, Heart, Wrench, Shirt,
  Utensils, ShoppingCart, Building, Leaf, PawPrint, Music, Clapperboard,
  Palette, Droplets, Landmark, Pizza, Sprout, Dumbbell, Baby,
  Wallet, Award, BadgeDollarSign, Banknote, Coins, CreditCard,
  HelpingHand, Hospital, Monitor, Plus, Receipt, Scale, ShoppingBag,
  Ticket, Train, TramFront, TreePalm, Truck, Tv, User, Users, Wifi
} from 'lucide-react';

const customIcon = (props: React.ComponentProps<'svg'>) => (
    React.createElement(
      'svg',
      {
        ...props,
        xmlns: 'http://www.w3.org/2000/svg',
        width: '24',
        height: '24',
        viewBox: '0 0 24 24',
        fill: 'none',
        stroke: 'currentColor',
        strokeWidth: '2',
        strokeLinecap: 'round',
        strokeLinejoin: 'round',
      },
      React.createElement('path', { d: 'M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6' })
    )
  );

export const potIcons = {
  necessities: Home,
  freedom: TrendingUp,
  saving: PiggyBank,
  education: BookOpen,
  play: Gamepad2,
  giving: Gift,
  custom: customIcon,
  briefcase: Briefcase,
  car: Car,
  plane: Plane,
  graduation: GraduationCap,
  heart: Heart,
  wrench: Wrench,
  shirt: Shirt,
  utensils: Utensils,
  cart: ShoppingCart,
  building: Building,
  leaf: Leaf,
  paw: PawPrint,
  music: Music,
  movie: Clapperboard,
  art: Palette,
  health: Droplets,
  culture: Landmark,
  pizza: Pizza,
  invest: Sprout,
  gym: Dumbbell,
  baby: Baby,
  wallet: Wallet,
  award: Award,
  tax: BadgeDollarSign,
  banknote: Banknote,
  coins: Coins,
  creditcard: CreditCard,
  charity: HelpingHand,
  hospital: Hospital,
  tech: Monitor,
  emergency: Plus,
  bills: Receipt,
  justice: Scale,
  shopping: ShoppingBag,
  event: Ticket,
  subway: Train,
  transport: TramFront,
  vacation: TreePalm,
  moving: Truck,
  entertainment: Tv,
  personal: User,
  family: Users,
  internet: Wifi,
};

export type PotIconKey = keyof typeof potIcons;

export const iconList: { key: PotIconKey; name: {ar: string, en: string}; icon: React.FC<any> }[] = [
  { key: 'necessities', name: {ar: 'المنزل', en: 'Home'}, icon: Home },
  { key: 'freedom', name: {ar: 'نمو', en: 'Growth'}, icon: TrendingUp },
  { key: 'saving', name: {ar: 'حصالة', en: 'Piggy Bank'}, icon: PiggyBank },
  { key: 'education', name: {ar: 'كتاب', en: 'Book'}, icon: BookOpen },
  { key: 'play', name: {ar: 'لعب', en: 'Play'}, icon: Gamepad2 },
  { key: 'giving', name: {ar: 'هدية', en: 'Gift'}, icon: Gift },
  { key: 'custom', name: {ar: 'مخصص', en: 'Custom'}, icon: customIcon },
  { key: 'briefcase', name: {ar: 'عمل', en: 'Work'}, icon: Briefcase },
  { key: 'car', name: {ar: 'سيارة', en: 'Car'}, icon: Car },
  { key: 'plane', name: {ar: 'سفر', en: 'Travel'}, icon: Plane },
  { key: 'graduation', name: {ar: 'تخرج', en: 'Graduation'}, icon: GraduationCap },
  { key: 'heart', name: {ar: 'حب', en: 'Love'}, icon: Heart },
  { key: 'wrench', name: {ar: 'صيانة', en: 'Maintenance'}, icon: Wrench },
  { key: 'shirt', name: {ar: 'ملابس', en: 'Clothing'}, icon: Shirt },
  { key: 'utensils', name: {ar: 'طعام', en: 'Dining'}, icon: Utensils },
  { key: 'cart', name: {ar: 'تسوق', en: 'Shopping Cart'}, icon: ShoppingCart },
  { key: 'building', name: {ar: 'عقار', en: 'Real Estate'}, icon: Building },
  { key: 'leaf', name: {ar: 'طبيعة', en: 'Nature'}, icon: Leaf },
  { key: 'paw', name: {ar: 'حيوانات أليفة', en: 'Pets'}, icon: PawPrint },
  { key: 'music', name: {ar: 'موسيقى', en: 'Music'}, icon: Music },
  { key: 'movie', name: {ar: 'أفلام', en: 'Movies'}, icon: Clapperboard },
  { key: 'art', name: {ar: 'فن', en: 'Art'}, icon: Palette },
  { key: 'health', name: {ar: 'صحة', en: 'Health'}, icon: Droplets },
  { key: 'culture', name: {ar: 'ثقافة', en: 'Culture'}, icon: Landmark },
  { key: 'pizza', name: {ar: 'أكل سريع', en: 'Fast Food'}, icon: Pizza },
  { key: 'invest', name: {ar: 'استثمار', en: 'Investment'}, icon: Sprout },
  { key: 'gym', name: {ar: 'نادي رياضي', en: 'Gym'}, icon: Dumbbell },
  { key: 'baby', name: {ar: 'طفل', en: 'Baby'}, icon: Baby },
  { key: 'wallet', name: {ar: 'محفظة', en: 'Wallet'}, icon: Wallet },
  { key: 'award', name: {ar: 'جائزة', en: 'Award'}, icon: Award },
  { key: 'tax', name: {ar: 'ضرائب', en: 'Taxes'}, icon: BadgeDollarSign },
  { key: 'banknote', name: {ar: 'كاش', en: 'Cash'}, icon: Banknote },
  { key: 'coins', name: {ar: 'عملات', en: 'Coins'}, icon: Coins },
  { key: 'creditcard', name: {ar: 'بطاقة ائتمان', en: 'Credit Card'}, icon: CreditCard },
  { key: 'charity', name: {ar: 'صدقة', en: 'Charity'}, icon: HelpingHand },
  { key: 'hospital', name: {ar: 'مستشفى', en: 'Hospital'}, icon: Hospital },
  { key: 'tech', name: {ar: 'تقنية', en: 'Technology'}, icon: Monitor },
  { key: 'emergency', name: {ar: 'طوارئ', en: 'Emergency'}, icon: Plus },
  { key: 'bills', name: {ar: 'فواتير', en: 'Bills'}, icon: Receipt },
  { key: 'justice', name: {ar: 'قانون', en: 'Justice'}, icon: Scale },
  { key: 'shopping', name: {ar: 'مشتريات', en: 'Shopping'}, icon: ShoppingBag },
  { key: 'event', name: {ar: 'مناسبة', en: 'Event'}, icon: Ticket },
  { key: 'subway', name: {ar: 'مترو', en: 'Subway'}, icon: Train },
  { key: 'transport', name: {ar: 'مواصلات', en: 'Transport'}, icon: TramFront },
  { key: 'vacation', name: {ar: 'إجازة', en: 'Vacation'}, icon: TreePalm },
  { key: 'moving', name: {ar: 'نقل', en: 'Moving'}, icon: Truck },
  { key: 'entertainment', name: {ar: 'ترفيه', en: 'Entertainment'}, icon: Tv },
  { key: 'personal', name: {ar: 'شخصي', en: 'Personal'}, icon: User },
  { key: 'family', name: {ar: 'عائلة', en: 'Family'}, icon: Users },
  { key: 'internet', name: {ar: 'إنترنت', en: 'Internet'}, icon: Wifi },
];
